apiVersion: apps/v1
kind: Deployment
metadata:
  name: racer-deployment
spec:
  selector:
    matchLabels:
      app: racer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: racer
    spec:
      containers:
      - name: racer
        image: dgslaughter/racer:latest
        ports:
        - containerPort: 80
