apiVersion: aprgoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dgslaughter/javascript-racer.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamesapce=true
    automated:
      selfHeal: true
      prune: true