apiVersion: apps/v1
kind: Deployment
metadata:
  name: racer-deployment
  annotations:
    "sidecar.jaegertracing.io/inject": "true" # <1>
spec:
  selector:
    matchLabels:
      app: racer
  replicas: 2 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: racer
    spec:
      containers:
      - name: racer
        image: docker.io/dgslaughter/racer:latest
        ports:
        - containerPort: 80
